# Generated by Django 5.0 on 2025-05-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_hire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
